In [3]:
from tensorflow.keras.datasets import cifar10
import tensorflow as tf
import numpy as np

In [4]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train = x_train.astype("float64") / 255.0
x_test  = x_test.astype('float64') / 255.0
x_train = tf.convert_to_tensor(x_train)
x_test = tf.convert_to_tensor(x_test)
x_train = (x_train.numpy())
x_test = (x_test.numpy())

In [6]:
y_train = y_train.reshape(-1)
y_test  = y_test.reshape(-1)
print(y_train.shape, y_test.shape)

(50000,) (10000,)


In [8]:
def processing(Y, n):
    y = np.zeros((Y.shape[0], n))
    for i in range(Y.shape[0]):
        y[i, int(Y[i])] = 1
    return y

y_train = processing(y_train,10)
y_test  = processing(y_test ,10)

In [9]:
print(y_train[:10])

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [11]:
from DNN import *

In [49]:
input = Input(shape=(32, 32, 3))
conv2d1 = Conv2D(filters=16, kernel_size=3, padding=1, activation='ReLU', prev_layer=input)
maxpooling1 = MaxPool2D(pool_size=2, prev_layer=conv2d1)
conv2d2 = Conv2D(filters=32, kernel_size=3, padding=1, activation='ReLU', prev_layer=maxpooling1)
maxpooling2 = MaxPool2D(pool_size=2, prev_layer=conv2d2)
flatten = Flatten(prev_layer=maxpooling2)
layer1 = Layer(shape=256, activation='ReLU', prev_layer=flatten)
layer2 = Layer(shape=64, activation='ReLU', prev_layer=layer1)
output = Layer(shape=10, activation='softmax', prev_layer=layer2)
model = Model(input=input, output=output)
model.compile(loss=Loss.CrossEntropy, learning_rate=0.001)

In [50]:
print(model.total_parameters)

423520


In [51]:
print(conv2d1.params)

448


In [52]:
print(layer1.params)

401408


In [53]:
print(flatten.shape)

1568


In [56]:
sx_train = x_train[:1000]
sx_test  = x_test[:50]
sy_train = y_train[:1000]
sy_test  = y_test[:50]

In [58]:
model.fit(sx_train, sy_train, batch_size=8, epochs=100)

KeyboardInterrupt: 